server:
  name: localhost
  port: 9090
  includePortInOauth2RedirectUri: true
  streamingServiceServer: localhost
  streamingServicePort: 8080
  streamingServiceUri: http://${server.streamingServiceServer}:${server.streamingServicePort}/api/streamvideoprovider

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            authorization-uri: http://${server.name}:${server.port}/custom-login
            user-name-attribute: email

okta:
  oauth2:
    issuer: https://login.vivelo.tv/oauth2/default
    clientId: 0oafem8k4O49jU0tM4x6
    clientSecret: YMohoBRPrEx4e5RHyeeQDqrulNZ5x8365lPhIuB2
    redirect-uri: /authorization-code/callback
    postLogoutRedirectUri: http://${server.name}:${server.port}/
    scopes:
    - openid
    - email
    - profile