server:
  port: 80

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            authorization-uri: http://vivelo.tv/custom-login
            user-name-attribute: email

okta:
  oauth2:
    issuer: https://dev-271413.okta.com/oauth2/default
    clientId: 0oak85iu6IokRnvSX4x6
    clientSecret: 3ofqZLeJFr_IZCB9j7Kt3QvclrcHB_NAzv1eWLXg
    redirect-uri: http://vivelo.tv/
    postLogoutRedirectUri: http://vivelo.tv/
    scopes:
    - openid
    - email
    - profile
