server:
  name: www.vivelo.tv
  port: 443
  includePortInOauth2RedirectUri: false
  streamingServiceServer: localhost
  streamingServicePort: 7070
  streamingServiceUri: http://${server.streamingServiceServer}:${server.streamingServicePort}/api/streamvideoprovider

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            authorization-uri: https://${server.name}:${server.port}/custom-login
            user-name-attribute: email

okta:
  oauth2:
    issuer: https://dev-271413.okta.com/oauth2/default
    clientId: 0oak85iu6IokRnvSX4x6
    clientSecret: 3ofqZLeJFr_IZCB9j7Kt3QvclrcHB_NAzv1eWLXg
    redirect-uri: /authorization-code/callback
    postLogoutRedirectUri: https://${server.name}:${server.port}/
    scopes:
    - openid
    - email
    - profile